[package]
name = "proton_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "proton_nif"
path = "src/lib.rs"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.pnet]
version = "0.35.0"

[dependencies.proton_err]
path = "../proton_err"

[features]
ethx = []
cndn = []