name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install DBus
      run: sudo apt-get install -y libdbus-1-dev
    - name: Initialize submodules
      run: git submodule init
    - name: Update submodules
      run: git submodule update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
